columnSuffix: null
handle: featured
instructions: 'Show this item in the homepage highlights.'
name: Featured
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
